service:
  name: ts-motile-runner

app: motile
org: wslyvh

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  environment:
    BITMEX_KEY_0: ${param:BITMEX_KEY_0}
    BITMEX_SECRET_0: ${param:BITMEX_SECRET_0}
    BITMEX_KEY_1: ${param:BITMEX_KEY_1}
    BITMEX_SECRET_1: ${param:BITMEX_SECRET_1}
    BOT_KEY_0: ${param:BOT_KEY_0}
    BOT_SECRET_0: ${param:BOT_SECRET_0}
    BOT_KEY_1: ${param:BOT_KEY_1}
    BOT_SECRET_1: ${param:BOT_SECRET_1}

functions:
  defaultFunction:
    handler: handler.defaultFunction
    events:
      - schedule: cron(0/10 * * * ? *)
