name: Run

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: yarn install
      - name: Run
        run: yarn start
        env:
          BOT_KEY_0: ${{ secrets.BOT_KEY_0 }}
          BOT_SECRET_0: ${{ secrets.BOT_SECRET_0 }}
          BOT_TYPE_0: ${{ secrets.BOT_TYPE_0 }}